Waleed Inventory And Sales/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Sales_And_Inventory_MIS.Models;
using Waleed_Inventory_And_Sales.Models;

namespace Waleed_Inventory_And_Sales.Controllers
{
    public class OrdersController : Controller
    {
        private DbContextClass db = new DbContextClass();

        // GET: Orders

        public ActionResult Search(string DateFrom, string DateTo)
        {
            if(DateFrom==null || DateTo==null)
            {
                var order = db.order.Include(o => o.customer).Include(o=>o.salelineitem);
                    return View(order.ToList());

            }
            DateTime datefrom = Convert.ToDateTime(DateFrom);
            DateTime dateto = Convert.ToDateTime(DateTo);

            var orders = (from ordr in db.order where ordr.orderDate>=datefrom && ordr.orderDate<=dateto select ordr).Include(s=>s.salelineitem).ToList();
            return View(orders);
        }

        public ActionResult SearchOrderById(string billno)
        {

            var orders = (from ordr in db.order where ordr.description.Contains(billno) select ordr).ToList();
            return View(orders);
        }


        public ActionResult Index()
        {
            var order = db.order.Include(o => o.customer).OrderBy(o => o.orderDate);
            return View(order.ToList());
        }
        public ActionResult DisplayOrders(int choice,int? id)
        {
            if (choice == 1)
            {
                var orderr = db.order.Include(o => o.customer).Where(o=>o.customerid==id);
                return View(orderr.ToList());

                //var order1 = db.order.Include(o => o.customer);

                //List<Order> idd = (from odr in order1 select odr).ToList();

                //Customer customer = db.Customers.Find(id);
                //var orderr = (from odr in db.order where odr.customerid == 1 select odr);
            }

            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        public ActionResult BillsForCustomer(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return RedirectToAction("DisplayOrders", new { choice= 1, id=id }); 
 
//            var order = db.order.Include(o => o.customer);
//            return View(order.ToList());
        }

        // GET: Orders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.order.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }

            Session["orderid"] = id;
            return RedirectToAction( "Index", "SalesLineItems");

        }

        public ActionResult AddItems(int? id)
        {
            return RedirectToAction("Create", "SalesLineItems");
        }
        public ActionResult ShowItems(int? id)
        {
            Session["orderid"] = id;
            return RedirectToAction("Index", "SalesLineItems");
        }
        public ActionResult Finish()
        {
            int orderid = int.Parse(Session["orderid"].ToString());
            
            var customer = (from orders in db.order where orders.id == orderid select orders.customer).FirstOrDefault();
            var order = (from orders in db.order where orders.id == orderid select orders).FirstOrDefault();

            customer.ammount = customer.ammount + order.total;
            db.Entry(customer).State = EntityState.Modified;
            db.SaveChanges();

            //Order Transaction Added
            Transaction transaction = new Transaction();
            transaction.Ammount = order.total;
            transaction.Balance = customer.ammount;
            transaction.Date = order.orderDate;
            transaction.Description = "";
            transaction.order = order;
            transaction.Orderid = order.id;
            transaction.Customer = customer;
            transaction.Customerid = customer.id;
            transaction.type = TransactionType.Credit;

            db.Transactions.Add(transaction);
            db.SaveChanges();

            if (order.paid.Equals(true))
            {
                SupplyOrder supply = new SupplyOrder();
                supply.description = order.description;
                supply.location = "Shop";
                supply.orderid = order.id;
                supply.supplyDate = order.orderDate;
                SupplyOrdersController s = new SupplyOrdersController();
                s.Create(supply);

                Payment payment = new Payment();
                payment.customerid = order.customerid;
                payment.Date = order.orderDate;
                payment.Ammount = order.total;
                payment.description = order.description;

                PaymentsController pay = new PaymentsController();
                pay.Create(payment);
            }
            else
            {
                if (Session["Supply"].ToString() == "on")
                {
                    SupplyOrder supply = new SupplyOrder();
                    supply.description = order.description;
                    supply.location = "Shop";
                    supply.orderid = order.id;
                    supply.supplyDate = order.orderDate;

                    SupplyOrdersController s = new SupplyOrdersController();
                    s.Create(supply);

                }
                if (Session["Payment"].ToString() == "on")
                {
                    Payment payment = new Payment();
                    payment.customerid = order.customerid;
                    payment.Date = order.orderDate;
                    payment.Ammount = order.total;
                    payment.description = order.description;

                    PaymentsController pay = new PaymentsController();
                    pay.Create(payment);
                }
            }
            ///Transaction
            return RedirectToAction("Index", "Customers");
        }

        // GET: Orders/Create
        public ActionResult Create()
        {
            ViewBag.customerid = new SelectList(db.Customers.OrderBy(s=>s.name), "id", "name");
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,orderDate,description,customerid,paid")] Order order,string Supply,string Payment,string shellsOrder)
        {

            if (ModelState.IsValid)
            {
                Switch.idsToSwitch = new List<int>();
                order.total = 0;
                db.order.Add(order);
                db.SaveChanges();
                Session["orderid"] = order.id;
                if (Supply == null)
                    Session["Supply"] = "off";
                else
                    Session["Supply"] = Supply;
                if(Payment==null)
                    Session["Payment"] = "off";
                else
                    Session["Payment"] = Payment;

               return RedirectToAction("Index");
            }

            ViewBag.customerid = new SelectList(db.Customers, "id", "name", order.customerid);
            return View(order);
        }

        // GET: Orders/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.order.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            ViewBag.customerid = new SelectList(db.Customers, "id", "name", order.customerid);
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,total,orderDate,customerid")] Order order)
        {
            if (ModelState.IsValid)
            {
                db.Entry(order).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.customerid = new SelectList(db.Customers, "id", "name", order.customerid);
            return View(order);
        }

        // GET: Orders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.order.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Order order = db.order.Find(id);
            db.order.Remove(order);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Waleed Inventory And Sales/Controllers/TransactionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Sales_And_Inventory_MIS.Models;
using Waleed_Inventory_And_Sales.Models;

namespace Waleed_Inventory_And_Sales.Controllers
{
    public class TransactionsController : Controller
    {
        private DbContextClass db = new DbContextClass();

        // GET: Transactions
        public ActionResult Index()
        {
            var transactions = db.Transactions.Include(t => t.Customer).Include(t => t.order).Include(t => t.Payment);
            return View(transactions.ToList());
        }

        // GET: Transactions
        public ActionResult CustomerTransactions(int? Customerid)
        {
            if(Customerid==null)
            {
                Session["Customer"] = null;
                Session["Search"] = true;
                return View(db.Transactions.Include(Trans=>Trans.Customer).OrderByDescending(o => o.Date).ToList());
            }
            Session["Search"] = null;
            Session["Customer"] = db.Customers.Where(cust => cust.id == Customerid).FirstOrDefault();
            List<Transaction> transactions = db.Transactions.Where(cust=>cust.Customerid==Customerid).Include(t => t.Customer).OrderByDescending(o=>o.Date).ToList();
            return View(transactions);
        }
        // GET: Transactions
        public ActionResult Search(string DateFrom, string DateTo)
        {
            if (DateFrom == null || DateTo == null)
            {
                return View(db.Transactions.Include(Trans => Trans.Customer).OrderByDescending(o=>o.Date).ToList());
            }
            DateTime datefrom = Convert.ToDateTime(DateFrom);
            DateTime dateto = Convert.ToDateTime(DateTo);

            Session["Customer"] = null;
            Session["Search"] = true;
            Session["Detailed"] = true;

            List<Transaction> transactions = db.Transactions.Where(trans => trans.Date >= datefrom && trans.Date<=dateto).Include(t => t.Customer).Include(trans => trans.Payment).Include(trans=>trans.order).Include(trans=>trans.order.salelineitem).OrderByDescending(o => o.Date).ToList();

            return View(transactions);
        }


        // GET: Transactions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Transaction transaction = db.Transactions.Find(id);
            if (transaction == null)
            {
                return HttpNotFound();
            }
            return View(transaction);
        }

        // GET: Transactions/Create
        public ActionResult Create()
        {
            ViewBag.Customerid = new SelectList(db.Customers, "id", "name");
            ViewBag.Orderid = new SelectList(db.order, "id", "description");
            ViewBag.Paymentid = new SelectList(db.Payments, "id", "description");
            return View();
        }

        // POST: Transactions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,Customerid,Orderid,Paymentid,Ammount,type,Balance,Description,Date")] Transaction transaction)
        {
            if (ModelState.IsValid)
            {
                db.Transactions.Add(transaction);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Customerid = new SelectList(db.Customers, "id", "name", transaction.Customerid);
            ViewBag.Orderid = new SelectList(db.order, "id", "description", transaction.Orderid);
            ViewBag.Paymentid = new SelectList(db.Payments, "id", "description", transaction.Paymentid);
            return View(transaction);
        }

        // GET: Transactions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Transaction transaction = db.Transactions.Find(id);
            if (transaction == null)
            {
                return HttpNotFound();
            }
            ViewBag.Customerid = new SelectList(db.Customers, "id", "name", transaction.Customerid);
            ViewBag.Orderid = new SelectList(db.order, "id", "description", transaction.Orderid);
            ViewBag.Paymentid = new SelectList(db.Payments, "id", "description", transaction.Paymentid);
            return View(transaction);
        }

        // POST: Transactions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,Customerid,Orderid,Paymentid,Ammount,type,Balance,Description,Date")] Transaction transaction)
        {
            if (ModelState.IsValid)
            {
                db.Entry(transaction).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Customerid = new SelectList(db.Customers, "id", "name", transaction.Customerid);
            ViewBag.Orderid = new SelectList(db.order, "id", "description", transaction.Orderid);
            ViewBag.Paymentid = new SelectList(db.Payments, "id", "description", transaction.Paymentid);
            return View(transaction);
        }

        // GET: Transactions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Transaction transaction = db.Transactions.Find(id);
            if (transaction == null)
            {
                return HttpNotFound();
            }
            return View(transaction);
        }

        // POST: Transactions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Transaction transaction = db.Transactions.Find(id);
            db.Transactions.Remove(transaction);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Waleed Inventory And Sales/Views/Transactions/Create.cshtml
@model Waleed_Inventory_And_Sales.Models.Transaction

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Transaction</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Customerid, "Customerid", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Customerid", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Customerid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Orderid, "Orderid", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Orderid", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Orderid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Paymentid, "Paymentid", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Paymentid", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Paymentid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ammount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ammount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ammount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.type, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Balance, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Balance, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Balance, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Waleed Inventory And Sales/Views/Transactions/CustomerTransactions.cshtml
@model IEnumerable<Waleed_Inventory_And_Sales.Models.Transaction>
@using Sales_And_Inventory_MIS.Models;
@using Waleed_Inventory_And_Sales.Models;
@{
    ViewBag.Title = "CustomerTransactions";
    Customer customer = (Customer)Session["Customer"];
    bool detail = false;
    if(Session["Detailed"]!=null)
    {
        detail = true;
        Session["Detailed"] = null;
    }
}
@using (Html.BeginForm("Search", "Transactions"))
{
    <b>From</b>
    <input class="form-control text-box single-line" data-val="true" data-val-date="The field Date must be a date." data-val-required="The Date field is required." id="Date" name="DateFrom" type="date" value="">
    <b>To</b>
    <input class="form-control text-box single-line" data-val="true" data-val-date="The field Date must be a date." data-val-required="The Date field is required." id="Date" name="DateTo" type="date" value="">

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Filter" class="btn btn-default" />
        </div>
    </div>

}

@if (Session["Search"] != null)
{
    <h2>Transaction History</h2>

}
@if (customer != null)
{
    <h2>Customer History</h2>
    <table class="table">
        <th> <b>Name:</b>@customer.name   </th>
        <th> <b>Contact:</b>@customer.mobile</th>
        <th> <b>Location:</b>@customer.Location   </th>
    </table>
}

<p>
    @*@Html.ActionLink("Create New", "Create")*@
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            Bill #
        </th>
        <th>
            Credit
        </th>
        <th>
            Debit
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Balance)
        </th>
        @if (Session["Search"] != null)
        {
            <th>
                Customer
            </th>

        }
        @if (detail)
        {
            <th>Items</th>
        }
        <th></th>
    </tr>

@foreach (var item in Model) {
    int credit = 0, debit = 0;
    if (item.type.Equals(TransactionType.Credit))
    {
        credit = item.Ammount;
    }
    if (item.type.Equals(TransactionType.Debit))
    {
        debit = item.Ammount;
    }
    <tr>
        <td>
             @item.Date.ToString("dd-MMM-yyyy")
        </td>
        <td>
            @if(item.Description.Equals("Returned"))
            {
                @item.Description
            }
            else if(item.type.Equals(TransactionType.Credit))
            {
                @item.order.description
            }
            else
            {
                @item.Payment.description
            }
        </td>
        <td>
            @credit
        </td>
        <td>
            @debit
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Balance)
        </td>
        @if (Session["Search"] != null)
        {
            <td>
                @item.Customer.name
            </td>

        }
        <td>

            @if (detail && item.type.Equals(TransactionType.Credit))
            {
                <ul style = "padding: 0; list-style-type:square">
                    @foreach (SalesLineItem sItem in item.order.salelineitem)
                    {
                    <li >@sItem.item.name<p>(@sItem.quantity)</p>
                    </li>
                    }
                </ul>
            }
        </td>

        <td>
            @if (item.Description.Equals("Returned"))
            {
                @Html.ActionLink("Details", "Details", "ReturnItems", new { id = item.id }, null)
            }
            else if (item.type.Equals(TransactionType.Credit))
            {
                @Html.ActionLink("Details", "Details", "Orders", new { id = item.id }, null)
            }
            else
            {
                @Html.ActionLink("Details", "Details", "Payments", new { id = item.id }, null)
            }

            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>

Waleed Inventory And Sales/Views/Transactions/Delete.cshtml
@model Waleed_Inventory_And_Sales.Models.Transaction

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Transaction</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Customer.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.order.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.order.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Payment.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Payment.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ammount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ammount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Balance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Balance)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Waleed Inventory And Sales/Views/Transactions/Details.cshtml
@model Waleed_Inventory_And_Sales.Models.Transaction

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Transaction</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Customer.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.order.)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.order.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Payment.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Payment.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ammount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ammount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Balance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Balance)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Waleed Inventory And Sales/Views/Transactions/Index.cshtml
@model IEnumerable<Waleed_Inventory_And_Sales.Models.Transaction>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Customer.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.order.description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Payment.description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ammount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.type)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Balance)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Customer.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.order.description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Payment.description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Ammount)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.type)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Balance)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>

Waleed Inventory And Sales/Views/Transactions/Search.cshtml
@Html.Partial("CustomerTransactions")