Waleed Inventory And Sales/Models/SupplyOrder.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using System.ComponentModel.DataAnnotations;

namespace Sales_And_Inventory_MIS.Models
{
    public class SupplyOrder
    {
        [Key]
        public int id{ get; set; }
        public virtual Order order { set; get; }
        public int orderid { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime supplyDate{ get; set; }
        public string location { get; set; }
        public string description { get; set; }
        public ICollection<SalesLineItem> salelineitem { get; set; }

    }
}

Waleed Inventory And Sales/Controllers/SupplyOrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Sales_And_Inventory_MIS.Models;
using Waleed_Inventory_And_Sales.App_Start;

namespace Waleed_Inventory_And_Sales.Controllers
{
    public class SupplyOrdersController : Controller
    {
        private DbContextClass db = new DbContextClass();

        public ActionResult Search(string DateFrom, string DateTo,string searchtype,string text)
        {
            if (searchtype.Contains("Filter"))
            {
                if (DateFrom == null || DateTo == null)
                {
                    var order = db.order.Include(o => o.customer);
                    return View(order.ToList());

                }
                DateTime datefrom = Convert.ToDateTime(DateFrom);
                DateTime dateto = Convert.ToDateTime(DateTo);
                var orders = (from supplyodr in db.SupplyOrders where supplyodr.supplyDate >= datefrom && supplyodr.supplyDate <= dateto select supplyodr).ToList();
                
                return View(orders);

            }
            var supplyorders= (from so in db.SupplyOrders where so.location.Contains(text) || so.order.customer.name.Contains(text) || 
                               so.order.description.Contains(text) || so.order.customer.mobile.Contains(text) select so).ToList();

            return View(supplyorders);
        }

        // GET: SupplyOrders
        public ActionResult Index()
        {
            var supplyOrders = db.SupplyOrders.Include(s => s.order);
            return View(supplyOrders.ToList());
        }

        // GET: SupplyOrders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SupplyOrder supplyOrder = db.SupplyOrders.Find(id);
            if (supplyOrder == null)
            {
                return HttpNotFound();
            }
            Session["orderid"] = supplyOrder.orderid;
            return RedirectToAction("Index", "SalesLineItems");

        }

        // GET: SupplyOrders/Create
        public ActionResult Create()
        {
            ViewBag.orderid = new SelectList(db.order.OrderBy(s => s.description), "id", "description");
            return View();
        }

        // POST: SupplyOrders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,orderid,supplyDate,location,description")] SupplyOrder supplyOrder)
        {
            if (ModelState.IsValid)
            {
                db.SupplyOrders.Add(supplyOrder);
                db.SaveChanges();                

                var items = (from SalesLineItems in db.salesLineItem where SalesLineItems.orderid == supplyOrder.orderid select SalesLineItems.item).Include(a=>a.product).ToList();
                List<SalesLineItem> sitems = (from SalesLineItems in db.salesLineItem where SalesLineItems.orderid == supplyOrder.orderid select SalesLineItems).ToList();

                int quantitycheck = 0;

                var itemShellsSupply = Switch.idsToSwitch;

                foreach (var itm in items)
                {
                    if (itemShellsSupply.Count == 0)
                    {
                        itm.quantity = itm.quantity - sitems.First().quantity;
                    }
                    else
                    {
                        Util.SellShell(itm, sitems.First().quantity, db);
                    }
                    if (itm.quantity < 0)
                    {
                        quantitycheck++;
                    }
                    db.Entry(itm).State = EntityState.Modified;
                    db.SaveChanges();
                    sitems.RemoveAt(0);
                }
                if ( quantitycheck> 0)
                {
                    return new JavaScriptResult { Script = "alert('Successfully registered');" };
                    //var script = "alert('Some Items Quantity goes negative');";
                    //return JavaScript(script);
                }

                return RedirectToAction("Index");
            }

            ViewBag.orderid = new SelectList(db.order, "id", "description", supplyOrder.orderid);
            return View(supplyOrder);
        }

        // GET: SupplyOrders/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SupplyOrder supplyOrder = db.SupplyOrders.Find(id);
            if (supplyOrder == null)
            {
                return HttpNotFound();
            }
            ViewBag.orderid = new SelectList(db.order, "id", "description", supplyOrder.orderid);
            return View(supplyOrder);
        }

        // POST: SupplyOrders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,orderid,supplyDate,location,description")] SupplyOrder supplyOrder)
        {
            if (ModelState.IsValid)
            {
                db.Entry(supplyOrder).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.orderid = new SelectList(db.order, "id", "description", supplyOrder.orderid);
            return View(supplyOrder);
        }

        // GET: SupplyOrders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SupplyOrder supplyOrder = db.SupplyOrders.Find(id);
            if (supplyOrder == null)
            {
                return HttpNotFound();
            }
            return View(supplyOrder);
        }

        // POST: SupplyOrders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SupplyOrder supplyOrder = db.SupplyOrders.Find(id);
            db.SupplyOrders.Remove(supplyOrder);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Waleed Inventory And Sales/Views/SupplyOrders/Create.cshtml
@model Sales_And_Inventory_MIS.Models.SupplyOrder

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SupplyOrder</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.orderid, "orderid", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("orderid", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.orderid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.supplyDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.supplyDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.supplyDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Waleed Inventory And Sales/Views/SupplyOrders/Delete.cshtml
@model Sales_And_Inventory_MIS.Models.SupplyOrder

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SupplyOrder</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.order.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.order.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.supplyDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.supplyDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Waleed Inventory And Sales/Views/SupplyOrders/Details.cshtml
@model Sales_And_Inventory_MIS.Models.SupplyOrder

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>SupplyOrder</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.order.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.order.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.supplyDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.supplyDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Waleed Inventory And Sales/Views/SupplyOrders/Edit.cshtml
@model Sales_And_Inventory_MIS.Models.SupplyOrder

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SupplyOrder</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.orderid, "orderid", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("orderid", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.orderid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.supplyDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.supplyDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.supplyDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Waleed Inventory And Sales/Views/SupplyOrders/Index.cshtml
@model IEnumerable<Sales_And_Inventory_MIS.Models.SupplyOrder>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm("Search", "SupplyOrders"))
{

    <b>From</b>
    <input class="form-control text-box single-line" data-val="true" data-val-date="The field Date must be a date." data-val-required="The Date field is required." id="Date" name="DateFrom" type="date" value="">
    <b>To</b>
    <input class="form-control text-box single-line" data-val="true" data-val-date="The field Date must be a date." data-val-required="The Date field is required." id="Date" name="DateTo" type="date" value="">

    <input type="hidden" value="Filter" name="searchtype">

    
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Filter" class="btn btn-default" />
        </div>
    </div>

}

@using (Html.BeginForm("Search", "SupplyOrders"))
{

    <b>From</b>
    <input type="text" name="text" placeholder="Search" class="btn btn-default" />           
    <input type="hidden" value="Search" name="searchtype">

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Search" class="btn btn-default" />
        </div>
    </div>

}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Order Des
        </th>
        <th>
            @Html.DisplayNameFor(model => model.supplyDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.location)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.description)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.order.description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.supplyDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.location)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.description)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>

Waleed Inventory And Sales/Views/SupplyOrders/Search.cshtml
@model IEnumerable<Sales_And_Inventory_MIS.Models.SupplyOrder>

@{
    ViewBag.Title = "Search";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Search</h2>
@using (Html.BeginForm("Search", "SupplyOrders"))
{

    <b>From</b>
    <input class="form-control text-box single-line" data-val="true" data-val-date="The field Date must be a date." data-val-required="The Date field is required." id="Date" name="DateFrom" type="date" value="">
    <b>To</b>
    <input class="form-control text-box single-line" data-val="true" data-val-date="The field Date must be a date." data-val-required="The Date field is required." id="Date" name="DateTo" type="date" value="">

    <input type="hidden" value="Filter" name="searchtype">


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Filter" class="btn btn-default" />
        </div>
    </div>

}

@using (Html.BeginForm("Search", "SupplyOrders"))
{

    <b>From</b>
    <input type="text" name="text" placeholder="Search" class="btn btn-default" />
    <input type="hidden" value="Search" name="searchtype">

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Search" class="btn btn-default" />
        </div>
    </div>

}


<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.order.description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.supplyDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.location)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.description)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.order.description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.supplyDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.location)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.description)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>