Waleed Inventory And Sales/Controllers/ExpensesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Sales_And_Inventory_MIS.Models;

namespace Waleed_Inventory_And_Sales.Controllers
{
    public class ExpensesController : Controller
    {
        public ActionResult SearchP()
        {
            return View();
        }
        public ActionResult Search(string DateFrom, string DateTo, string searchtype, string text)
        {
            if (searchtype.Contains("Filter"))
            {
                if (DateFrom == null || DateTo == null)
                {
                    var order = db.order.Include(o => o.customer);
                    return View(order.ToList());

                }
                DateTime datefrom = Convert.ToDateTime(DateFrom);
                DateTime dateto = Convert.ToDateTime(DateTo);
                var expenses = (from expns in db.expense where expns.Date >= datefrom && expns.Date <= dateto select expns).ToList();

                return View(expenses);

            }
            else if (searchtype.Contains("search"))
            {
                var expn = (from expnse in db.expense
                            where expnse.description.Contains(text) || expnse.type.name.Contains(text)
                            || expnse.entity.name.Contains(text)
                            select expnse).ToList();

                return View(expn);
            }
            else if (searchtype.Contains("entitydate"))
            {
                DateTime datefrom = Convert.ToDateTime(DateFrom);
                DateTime dateto = Convert.ToDateTime(DateTo);

                var expn = (from expnse in db.expense
                            where expnse.entity.name.Contains(text) && expnse.Date >= datefrom && expnse.Date <= dateto
                            select expnse).ToList();

                return View(expn);
            }
            else if (searchtype.Contains("typedate"))
            {
                DateTime datefrom = Convert.ToDateTime(DateFrom);
                DateTime dateto = Convert.ToDateTime(DateTo);

                var expn = (from expnse in db.expense
                            where expnse.entity.name.Contains(text) && expnse.Date >= datefrom && expnse.Date <= dateto
                            select expnse).ToList();

                return View(expn);
            }
            else if(searchtype.Contains("type"))
            {
                var expn = (from expnse in db.expense
                            where expnse.type.name.Contains(text)
                            select expnse).ToList();

                return View(expn);
            }
            else if (searchtype.Contains("entity"))
            {
                var expn = (from expnse in db.expense
                            where expnse.entity.name.Contains(text)
                            select expnse).ToList();

                return View(expn);
            }
            return View();
        }

        private DbContextClass db = new DbContextClass();

        // GET: Expenses
        public ActionResult Index()
        {
            var expense = db.expense.Include(e => e.entity).Include(e => e.type);
            return View(expense.ToList());
        }

        // GET: Expenses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Expense expense = db.expense.Find(id);
            if (expense == null)
            {
                return HttpNotFound();
            }
            return View(expense);
        }

        // GET: Expenses/Create
        public ActionResult Create()
        {
            ViewBag.entityId = new SelectList(db.entity.OrderBy(s => s.name), "id", "name");
            ViewBag.typeId = new SelectList(db.expenseType.OrderBy(s => s.name), "id", "name");
            return View();
        }

        // POST: Expenses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,typeId,entityId,Date,description,Ammount")] Expense expense)
        {
            if (ModelState.IsValid)
            {
                db.expense.Add(expense);
                db.SaveChanges();

                Global.Money = Global.Money - expense.Ammount;
                return RedirectToAction("Index");
            }

            ViewBag.entityId = new SelectList(db.entity, "id", "name", expense.entityId);
            ViewBag.typeId = new SelectList(db.expenseType, "id", "name", expense.typeId);
            return View(expense);
        }

        // GET: Expenses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Expense expense = db.expense.Find(id);
            if (expense == null)
            {
                return HttpNotFound();
            }
            ViewBag.entityId = new SelectList(db.entity, "id", "name", expense.entityId);
            ViewBag.typeId = new SelectList(db.expenseType, "id", "name", expense.typeId);
            return View(expense);
        }

        // POST: Expenses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,typeId,entityId,Date,description,Ammount")] Expense expense)
        {
            if (ModelState.IsValid)
            {
                db.Entry(expense).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.entityId = new SelectList(db.entity, "id", "name", expense.entityId);
            ViewBag.typeId = new SelectList(db.expenseType, "id", "name", expense.typeId);
            return View(expense);
        }

        // GET: Expenses/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Expense expense = db.expense.Find(id);
            if (expense == null)
            {
                return HttpNotFound();
            }
            return View(expense);
        }

        // POST: Expenses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Expense expense = db.expense.Find(id);
            db.expense.Remove(expense);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Waleed Inventory And Sales/Views/Expenses/Create.cshtml
@model Sales_And_Inventory_MIS.Models.Expense

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Expense</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.typeId, "typeId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("typeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.typeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.entityId, "entityId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("entityId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.entityId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ammount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ammount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ammount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Waleed Inventory And Sales/Views/Expenses/Delete.cshtml
@model Sales_And_Inventory_MIS.Models.Expense

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Expense</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.entity.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.entity.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.type.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.type.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ammount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ammount)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Waleed Inventory And Sales/Views/Expenses/Details.cshtml
@model Sales_And_Inventory_MIS.Models.Expense

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Expense</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.entity.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.entity.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.type.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.type.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ammount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ammount)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Waleed Inventory And Sales/Views/Expenses/Edit.cshtml
@model Sales_And_Inventory_MIS.Models.Expense

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Expense</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.typeId, "typeId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("typeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.typeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.entityId, "entityId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("entityId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.entityId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ammount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ammount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ammount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Waleed Inventory And Sales/Views/Expenses/Index.cshtml
@model IEnumerable<Sales_And_Inventory_MIS.Models.Expense>
@using Sales_And_Inventory_MIS.Models;

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<a href="~/ExpenseTypes/Index" class="btn btn-block btn-danger">Type</a>
<a href="~/Entities/Index" class="btn btn-block btn-danger">Entity</a>
<a href="~/Expenses/SearchP" class="btn btn-block btn-danger">Search</a>
<h2>Rupees in Hand:</h2>@Global.Money
<h2>Index</h2>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.entity.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.type.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ammount)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.entity.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.type.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Ammount)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>

Waleed Inventory And Sales/Views/Expenses/Search.cshtml
@model IEnumerable<Sales_And_Inventory_MIS.Models.Expense>

@{
    ViewBag.Title = "Search";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Search</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.entity.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.type.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ammount)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.entity.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.type.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Ammount)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>

Waleed Inventory And Sales/Views/Expenses/SearchP.cshtml
@model Sales_And_Inventory_MIS.Models.Expense
@using Sales_And_Inventory_MIS.Models
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm("Search", "Expenses"))
{

    <b>From</b>
    <input class="form-control text-box single-line" data-val="true" data-val-date="The field Date must be a date." data-val-required="The Date field is required." id="Date" name="DateFrom" type="date" value="">
    <b>To</b>
    <input class="form-control text-box single-line" data-val="true" data-val-date="The field Date must be a date." data-val-required="The Date field is required." id="Date" name="DateTo" type="date" value="">

    <input type="hidden" value="Filter" name="searchtype">

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Filter" class="btn btn-default" />
        </div>
    </div>

}

@using (Html.BeginForm("Search", "Expenses"))
{

    <input name="text" placeholder="text" type="text" />
    <input type="hidden" value="search" name="searchtype">

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Filter" class="btn btn-default" />
        </div>
    </div>

}

@using (Html.BeginForm("Search", "Expenses"))
{ 
     @Html.AntiForgeryToken()
  
       DbContextClass db = new DbContextClass();

       
    <select name="type">
        @foreach(var type in db.expenseType)
        {
            <option>@type.name</option>
        }
    </select>

    <input type="hidden" value="type" name="searchtype">

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Filter" class="btn btn-default" />
        </div>
    </div>

}
@using (Html.BeginForm("Search", "Expenses"))
{
    @Html.AntiForgeryToken()

    DbContextClass db = new DbContextClass();

    <select name="entity">
        @foreach (var type in db.entity)
        {
            <option value="@type.name">@type.name</option>
        }
    </select>

    <input type="hidden" value="entity" name="searchtype">

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Filter" class="btn btn-default" />
        </div>
    </div>

}

@using (Html.BeginForm("Search", "Expenses"))
{
    <b>From</b>
    <input class="form-control text-box single-line" data-val="true" data-val-date="The field Date must be a date." data-val-required="The Date field is required." id="Date" name="DateFrom" type="date" value="">
    <b>To</b>
    <input class="form-control text-box single-line" data-val="true" data-val-date="The field Date must be a date." data-val-required="The Date field is required." id="Date" name="DateTo" type="date" value="">

    DbContextClass db = new DbContextClass();


    <select name="type">
        @foreach (var type in db.expenseType)
        {
            <option value="@type.name">@type.name</option>
        }
    </select>

    <input type="hidden" value="typedate" name="searchtype">

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Filter" class="btn btn-default" />
        </div>
    </div>

}
@using (Html.BeginForm("Search", "Expenses"))
{
    <b>From</b>
    <input class="form-control text-box single-line" data-val="true" data-val-date="The field Date must be a date." data-val-required="The Date field is required." id="Date" name="DateFrom" type="date" value="">
    <b>To</b>
    <input class="form-control text-box single-line" data-val="true" data-val-date="The field Date must be a date." data-val-required="The Date field is required." id="Date" name="DateTo" type="date" value="">

    DbContextClass db = new DbContextClass();

    <select name="entity">
        @foreach (var type in db.entity)
        {
            <option>@type.name</option>
        }
    </select>

    <input type="hidden" value="entitydate" name="searchtype">

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Filter" class="btn btn-default" />
        </div>
    </div>

}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>